# Netlify Configuration File

# Build settings
[build]
  publish = "/"
  command = "# no build command needed"

# Identity settings
[identity]
  enable = true

# Git Gateway settings
[git-gateway]
  enable = true

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin"]}

# Asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
