# Netlify configuration file for Fershman Financial

# Build settings
[build]
  publish = "/"
  command = ""

# Environment variables will be set in the Netlify dashboard
# CONTENTFUL_SPACE_ID
# CONTENTFUL_ACCESS_TOKEN

# Redirect all routes to index.html for SPA-like navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  query = {path = ":path"}
  conditions = {Role = ["admin"]}

# Proper redirects for multi-page structure
[[redirects]]
  from = "/pages/*"
  to = "/pages/:splat"
  status = 200

[[redirects]]
  from = "/articles/*"
  to = "/articles/:splat"
  status = 200

# Headers to improve security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com https://cdnjs.cloudflare.com https://images.unsplash.com; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; img-src 'self' data: https://images.unsplash.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com;"

# Asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
