backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "select", options: ["Markets", "Analysis", "Policy & Regulation", "Opinion"] }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Content", name: "body", widget: "markdown" }
